server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  location /health {
    proxy_pass http://backend:3001/health;
  }

  location /api {
    proxy_pass http://backend:3001/api;
  }
}